"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['wfGui.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,'includes':['sip','PyQt4','PyQt4.QtCore','PyQt4.QtGui','PyQt4.QtWebKit','PyQt4.QtNetwork']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
